docker:
- docker/**/*

kubernetes:
- templates/**/*

configmap: 
- templates/configmap/**/*

deployments: 
- templates/deployments/**/*

secrets: 
- templates/secrets/**/*

services: 
- templates/services/**/*
